baseURL = 'https://weiren.org/'
languageCode = 'zh-tw'
title = 'Wet / Rain'
description = "Wayne's blog"
theme = 'PaperMod'
enableRobotsTXT = true

[permalinks]
  posts = '/:year/:slug/'


[params]
  ShowPostNavLinks = true
  defaultTheme = "auto"
  disableThemeToggle = false
  author = "Wayne"
  env = "production"
  images = ["https://weiren.b-cdn.net/blog-images/common/banner_1200.jpg"]
  showToc = false
  tocOpen = false

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[[menu.main]]
  name = "Home | 首頁"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts | 文章"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags | 標籤"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Categories | 分類"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "About | 關於這裡"
  url = "/about/"
  weight = 5

[[menu.main]]
  name = "RSS | 訂閱"
  url = "/index.xml"
  weight = 6

[[menu.main]]
  identifier = "search"
  name = "🔍 搜尋"
  url = "/search/"
  weight = 10


[outputs]
  home = ["HTML", "RSS", "JSON"]

