baseURL = "https://weiren.org/"
languageCode = 'zh-tw'
title = 'Wet / Rain'
theme = 'PaperMod'
copyright = "© {year} Wei-Jen Tseng. Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)."

[params]
  description = "wei-ren / wei-jen 's blog"
  author = "Wei-Jen"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  cdnURL = "https://weiren.b-cdn.net/blog-images/posts"


[params.analytics.goatcounter]
  code = "weiren"
 
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
  Title = "Wet / Rain"
  Content = "wei-ren / wei-jen 's blog"

[params.profileMode]
  enabled = false

[permalinks]
  posts = "/:year/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]  # 加入 JSON 來產生搜尋索引


[[menu.main]]
  name = "Home | 首頁"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts | 文章"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags | 標籤"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Categories | 分類"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "About | 關於這裡"
  url = "/about/"
  weight = 5

[[menu.main]]
  identifier = "search"
  name = "🔍 搜尋"
  url = "/search/"
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
